
export const FETCH_ISSUES_REQUESTED = 'FETCH_ISSUES_REQUESTED';
export const FETCH_ISSUES_SUCCESS = 'FETCH_ISSUES_SUCCESS';

export const UPDATE_ISSUE_REQUESTED = 'UPDATE_ISSUE_REQUESTED';
export const UPDATE_ISSUE_SUCCESS = 'UPDATE_ISSUE_SUCCESS';
